### ISSUE TITLE
core: frontend: logs: It's loading forever!

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/companion-docker#665] opened 2021-11-17 18:20 UTC
We need to check what is the issue, got the report from Blake

**Comment by patrickelectric** [comment] 2021-11-18 10:02
![image](https://user-images.githubusercontent.com/1215497/142394170-9ba0f833-0e93-42f5-94d7-a27f9be8325d.png)

**Comment by rafaellehmkuhl** [comment] 2021-11-18 11:50
Duplicate of #619

**Closed** 2021-11-18 11:52 UTC
Labels: bug, core, must-have, P0 - Critical Priority
