### ISSUE TITLE
core: ardupilot-manager: Validate firmwares before running (and reinstall if not)

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/companion-docker#622] opened 2021-10-27 19:03 UTC
![image](https://user-images.githubusercontent.com/1215497/139130113-063eefd2-e9e8-43b7-bff1-8c958104defc.png)

**Comment by rafaellehmkuhl** [comment] 2021-12-01 16:41
Duplicate of #538

**Closed by rafaellehmkuhl** 2021-12-01 16:41 UTC
Labels: bug, core, P1 - Important Pirority
