### ISSUE TITLE
core: ardupilot-manager: Shows no endpoint in new image

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/companion-docker#254] opened 2021-05-19 18:24 UTC
![image](https://user-images.githubusercontent.com/1215497/118864416-597f3680-b8b6-11eb-824e-18dfc57e927e.png)

**Comment by rafaellehmkuhl** [comment] 2021-05-19 18:27
Duplicate of #240

**Comment by patrickelectric** [comment] 2021-05-20 11:51
Default endpoint != of QGC supported endpoint as we have discussed

**Comment by patrickelectric** [comment] 2021-05-20 11:52
Related to #240 and #255

**Closed** 2021-05-21 21:25 UTC
Labels: bug, core
