### ISSUE TITLE
ardupilot parameters are not saved after power cycle or companion reboot

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/companion-docker#302] opened 2021-06-03 17:24 UTC

**Comment by Williangalvani** [comment] 2021-06-03 17:53
This seems to be due to an issue we fixed in master a while ago:
https://github.com/ArduPilot/ardupilot/pull/15606

**Comment by Williangalvani** [comment] 2021-06-03 18:29
This is a build of master from right now (c61570697140633d0fb3d545ebeae87f4c5174d0)


[ardusub.zip](https://github.com/bluerobotics/companion-docker/files/6593596/ardusub.zip)

**Comment by jaxxzer** [comment] 2021-06-03 18:45
> is the build in "https://s3.amazonaws.com/downloads.bluerobotics.com/ardusub/navigator/ardusub" custom?

yes

**Comment by jaxxzer** [comment] 2021-06-03 18:47
> we should use ardusub master with navigator for now or backport this

ok, I can handle it.

**Comment by Williangalvani** [comment] 2021-06-03 18:50
well. master seems to be failing too, here.

**Comment by Williangalvani** [comment] 2021-06-03 18:53
![image](https://user-images.githubusercontent.com/4013804/120697171-c7fdf000-c483-11eb-9500-ee8825d76adb.png)

**Comment by patrickelectric** [comment] 2021-06-03 19:32
The problem is the spaces around the arguments, I'll send PR. 
![image](https://user-images.githubusercontent.com/1215497/120701468-ddbde600-c480-11eb-9172-b249851187cf.png)

**Closed** 2021-06-03 20:39 UTC
